name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
version: 1.0.3
homepage: https://github.com/LuisThein
repository: https://github.com/LuisThein/platform_maps_flutter
issue_tracker: https://github.com/LuisThein/platform_maps_flutter/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.1
  google_maps_flutter_platform_interface: ^2.0.3
  # Fixes a print statement that is not yet published to pub.dev
  apple_maps_flutter:
    git:
      url: https://github.com/LuisThein/apple_maps_flutter
      ref: 866ff78adcd83c1b5c8057fc705a29bfeea8cad9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
